WITH TAB AS (
SELECT OWNER, TABLE_NAME, NUM_ROWS
     , PCT_FREE, PCT_USED
     , TRUNC((100-PCT_FREE)*0.01*AVG_ROW_LEN*NUM_ROWS/1024/1024,2) REQUEST
     , TRUNC(BLOCKS*8/1024,2) ACTUAL
FROM ALL_TABLES)
SELECT OWNER, TABLE_NAME, NUM_ROWS, REQUEST, ACTUAL, ACTUAL-REQUEST RECOV
      ,PCT_FREE, PCT_USED
FROM TAB 
WHERE OWNER='ASLF_IN' AND TABLE_NAME IN ('AVLMEMBERS','AVLATTRIBVALUES','AVLMEMBERTRANS','AVLMEMBERTRANSDETAIL')
ORDER BY RECOV DESC;